name: Deploy Data Pipeline Function
on:
  push:
    branches: [ "main" ]
    paths:
      - 'flask-app/**'
      - '.github/workflows/pipeline-app.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RG:         ${{ vars.AZ_RG }}
      ACA:        ${{ vars.AZ_ACA }}
      ACR:        ${{ vars.AZ_ACR }}
      ACR_LOGIN:  ${{ vars.AZ_ACR_LOGIN }}
      IMAGE_NAME: ${{ vars.AZ_IMAGE }}
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: ACR Login with token
        run: |
          TOKEN=$(az acr login --name "$ACR" --expose-token --output tsv --query accessToken)
          echo "${TOKEN}" | docker login "$ACR_LOGIN" --username 00000000-0000-0000-0000-000000000000 --password-stdin
          
      - name: Who am I?
        run: az account show -o table

      - name: Build & push image
        run: |
          TAG=${{ github.sha }}
          IMAGE="$ACR_LOGIN/$IMAGE_NAME:$TAG"
          docker build -t "$IMAGE" flask-app/.
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Update Container App
        run: |
          az containerapp update \
            --resource-group "$RG" \
            --name "$ACA" \
            --image "$IMAGE"
