name: Deploy Data Pipeline Function
on:
  push:
    branches: [ "main" ]
    paths:
      - 'flask-app/**'
      - '.github/workflows/pipeline-app.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RG:         ${{ vars.AZ_RG }}
      ACA:        ${{ vars.AZ_ACA }}
      ACR:        ${{ vars.AZ_ACR }}
      ACR_LOGIN:  ${{ vars.AZ_ACR_LOGIN }}
      IMAGE_NAME: ${{ vars.AZ_IMAGE }}
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & push image
        run: |
          TAG=${{ github.sha }}
          IMAGE="$ACR_LOGIN/$IMAGE_NAME:$TAG"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Update Container App
        run: |
          az containerapp update \
            --resource-group "$RG" \
            --name "$ACA" \
            --image "$IMAGE"
